cacheFolder: ~/.yarn-cache

enableTelemetry: false

logFilters:
  - code: YN0000
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.12.0.cjs
